#!/bin/bash

set -eu -o pipefail

xrandr --output HDMI-0 --off
xrandr --output HDMI-1 --off
xrandr --output HDMI-0 --mode 1920x1080 --left-of HDMI-1 --noprimary
xrandr --output HDMI-1 --mode 1920x1080 --right-of HDMI-0 --primary

